env:
  es6: true
  browser: true
  commonjs: true

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - react

extends:
  - htmlacademy/es6
  - plugin:react/recommended

settings:
  react:
    version: '16'

globals:
  __dirname: true
